import { OptionsNode } from '@/types';

export const ELEMENT_UI_DEMO_HIERARCHY: OptionsNode[] = [{
    value: 'guide',
    label: 'Guide',
    linkedAnnotation: null,
    children: [{
        value: 'disciplines',
        label: 'Disciplines',
        linkedAnnotation: null,
        children: [{
            value: 'consistency',
            label: 'Consistency',
            linkedAnnotation: null,
        }, {
            value: 'feedback',
            label: 'Feedback',
            linkedAnnotation: null,
        }, {
            value: 'efficiency',
            label: 'Efficiency',
            linkedAnnotation: null,
        }, {
            value: 'controllability',
            label: 'Controllability',
            linkedAnnotation: null,
        }]
    }, {
        value: 'navigation',
        linkedAnnotation: null,
        label: 'Navigation',
        children: [{
            value: 'side nav',
            label: 'Side Navigation',
            linkedAnnotation: null,
        }, {
            value: 'top nav',
            label: 'Top Navigation',
            linkedAnnotation: null,
        }]
    }]
}, {
    value: 'component',
    label: 'Component',
    linkedAnnotation: null,
    children: [{
        value: 'basic',
        label: 'Basic',
        linkedAnnotation: null,
        children: [{
            value: 'layout',
            label: 'Layout',
            linkedAnnotation: null,
        }, {
            value: 'color',
            label: 'Color',
            linkedAnnotation: null,
        }, {
            value: 'typography',
            label: 'Typography',
            linkedAnnotation: null,
        }, {
            value: 'icon',
            label: 'Icon',
            linkedAnnotation: null,
        }, {
            value: 'button',
            label: 'Button',
            linkedAnnotation: null,
        }]
    }, {
        value: 'form',
        label: 'Form',
        linkedAnnotation: null,
        children: [{
            value: 'radio',
            label: 'Radio',
            linkedAnnotation: null,
        }, {
            value: 'checkbox',
            label: 'Checkbox',
            linkedAnnotation: null,
        }, {
            value: 'input',
            label: 'Input',
            linkedAnnotation: null,
        }, {
            value: 'input-number',
            label: 'InputNumber',
            linkedAnnotation: null,
        }, {
            value: 'select',
            label: 'Select',
            linkedAnnotation: null,
        }, {
            value: 'cascader',
            label: 'Cascader',
            linkedAnnotation: null,
        }, {
            value: 'switch',
            label: 'Switch',
            linkedAnnotation: null,
        }, {
            value: 'slider',
            label: 'Slider',
            linkedAnnotation: null,
        }, {
            value: 'time-picker',
            label: 'TimePicker',
            linkedAnnotation: null,
        }, {
            value: 'date-picker',
            label: 'DatePicker',
            linkedAnnotation: null,
        }, {
            value: 'datetime-picker',
            label: 'DateTimePicker',
            linkedAnnotation: null,
        }, {
            value: 'upload',
            label: 'Upload',
            linkedAnnotation: null,
        }, {
            value: 'rate',
            label: 'Rate',
            linkedAnnotation: null,
        }, {
            value: 'form',
            label: 'Form',
            linkedAnnotation: null,
        }]
    }, {
        value: 'data',
        label: 'Data',
        linkedAnnotation: null,
        children: [{
            value: 'table',
            label: 'Table',
            linkedAnnotation: null,
        }, {
            value: 'tag',
            label: 'Tag',
            linkedAnnotation: null,
        }, {
            value: 'progress',
            label: 'Progress',
            linkedAnnotation: null,
        }, {
            value: 'tree',
            label: 'Tree',
            linkedAnnotation: null,
        }, {
            value: 'pagination',
            label: 'Pagination',
            linkedAnnotation: null,
        }, {
            value: 'badge',
            label: 'Badge',
            linkedAnnotation: null,
        }]
    }, {
        value: 'notice',
        label: 'Notice',
        linkedAnnotation: null,
        children: [{
            value: 'alert',
            label: 'Alert',
            linkedAnnotation: null,
        }, {
            value: 'loading',
            label: 'Loading',
            linkedAnnotation: null,
        }, {
            value: 'message',
            label: 'Message',
            linkedAnnotation: null,
        }, {
            value: 'message-box',
            label: 'MessageBox',
            linkedAnnotation: null,
        }, {
            value: 'notification',
            label: 'Notification',
            linkedAnnotation: null,
        }]
    }, {
        value: 'navigation',
        label: 'Navigation',
        linkedAnnotation: null,
        children: [{
            value: 'menu',
            label: 'NavMenu',
            linkedAnnotation: null,
        }, {
            value: 'tabs',
            label: 'Tabs',
            linkedAnnotation: null,
        }, {
            value: 'breadcrumb',
            label: 'Breadcrumb',
            linkedAnnotation: null,
        }, {
            value: 'dropdown',
            label: 'Dropdown',
            linkedAnnotation: null,
        }, {
            value: 'steps',
            label: 'Steps',
            linkedAnnotation: null,
        }]
    }, {
        value: 'others',
        label: 'Others',
        linkedAnnotation: null,
        children: [{
            value: 'dialog',
            label: 'Dialog',
            linkedAnnotation: null,
        }, {
            value: 'tooltip',
            label: 'Tooltip',
            linkedAnnotation: null,
        }, {
            value: 'popover',
            label: 'Popover',
            linkedAnnotation: null,
        }, {
            value: 'card',
            label: 'Card',
            linkedAnnotation: null,
        }, {
            value: 'carousel',
            label: 'Carousel',
            linkedAnnotation: null,
        }, {
            value: 'collapse',
            label: 'Collapse',
            linkedAnnotation: null,
        }]
    }]
}, {
    value: 'resource',
    label: 'Resource',
    linkedAnnotation: null,
    children: [{
        value: 'axure',
        label: 'Axure Components',
        linkedAnnotation: null,
    }, {
        value: 'sketch',
        label: 'Sketch Templates',
        linkedAnnotation: null,
    }, {
        value: 'docs',
        label: 'Design Documentation',
        linkedAnnotation: null,
    }]
}];
